// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package pers.protobuf;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string dnum = 1;
    /**
     * <code>required string dnum = 1;</code>
     */
    boolean hasDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    String getDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    com.google.protobuf.ByteString
        getDnumBytes();

    // required string length = 2;
    /**
     * <code>required string length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>required string length = 2;</code>
     */
    String getLength();
    /**
     * <code>required string length = 2;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    // required string type = 3;
    /**
     * <code>required string type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     */
    String getType();
    /**
     * <code>required string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string date = 4;
    /**
     * <code>required string date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 4;</code>
     */
    String getDate();
    /**
     * <code>required string date = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code pers.protobuf.PhoneDetail}
   */
  public static final class PhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements PhoneDetailOrBuilder {
    // Use PhoneDetail.newBuilder() to construct.
    private PhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneDetail defaultInstance;
    public static PhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              dnum_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              length_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              date_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.protobuf.Phone.PhoneDetail.class, pers.protobuf.Phone.PhoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<PhoneDetail>() {
      public PhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneDetail(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PhoneDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string dnum = 1;
    public static final int DNUM_FIELD_NUMBER = 1;
    private Object dnum_;
    /**
     * <code>required string dnum = 1;</code>
     */
    public boolean hasDnum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public String getDnum() {
      Object ref = dnum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dnum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDnumBytes() {
      Object ref = dnum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private Object length_;
    /**
     * <code>required string length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string length = 2;</code>
     */
    public String getLength() {
      Object ref = length_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          length_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string length = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      Object ref = length_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private Object type_;
    /**
     * <code>required string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private Object date_;
    /**
     * <code>required string date = 4;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string date = 4;</code>
     */
    public String getDate() {
      Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      dnum_ = "";
      length_ = "";
      type_ = "";
      date_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDnum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLengthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDateBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLengthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pers.protobuf.Phone.PhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pers.protobuf.Phone.PhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pers.protobuf.Phone.PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pers.protobuf.Phone.PhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pers.protobuf.PhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pers.protobuf.Phone.PhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.protobuf.Phone.PhoneDetail.class, pers.protobuf.Phone.PhoneDetail.Builder.class);
      }

      // Construct using pers.protobuf.Phone.PhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dnum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
      }

      public pers.protobuf.Phone.PhoneDetail getDefaultInstanceForType() {
        return pers.protobuf.Phone.PhoneDetail.getDefaultInstance();
      }

      public pers.protobuf.Phone.PhoneDetail build() {
        pers.protobuf.Phone.PhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pers.protobuf.Phone.PhoneDetail buildPartial() {
        pers.protobuf.Phone.PhoneDetail result = new pers.protobuf.Phone.PhoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dnum_ = dnum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.protobuf.Phone.PhoneDetail) {
          return mergeFrom((pers.protobuf.Phone.PhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.protobuf.Phone.PhoneDetail other) {
        if (other == pers.protobuf.Phone.PhoneDetail.getDefaultInstance()) return this;
        if (other.hasDnum()) {
          bitField0_ |= 0x00000001;
          dnum_ = other.dnum_;
          onChanged();
        }
        if (other.hasLength()) {
          bitField0_ |= 0x00000002;
          length_ = other.length_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000008;
          date_ = other.date_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDnum()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.protobuf.Phone.PhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.protobuf.Phone.PhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string dnum = 1;
      private Object dnum_ = "";
      /**
       * <code>required string dnum = 1;</code>
       */
      public boolean hasDnum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public String getDnum() {
        Object ref = dnum_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dnum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDnumBytes() {
        Object ref = dnum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dnum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder clearDnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dnum_ = getDefaultInstance().getDnum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }

      // required string length = 2;
      private Object length_ = "";
      /**
       * <code>required string length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string length = 2;</code>
       */
      public String getLength() {
        Object ref = length_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string length = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder setLength(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }

      // required string type = 3;
      private Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // required string date = 4;
      private Object date_ = "";
      /**
       * <code>required string date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string date = 4;</code>
       */
      public String getDate() {
        Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder setDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pers.protobuf.PhoneDetail)
    }

    static {
      defaultInstance = new PhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pers.protobuf.PhoneDetail)
  }

  public interface DayOfPhoneOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .pers.protobuf.PhoneDetail DayPhone = 1;
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    java.util.List<pers.protobuf.Phone.PhoneDetail> 
        getDayPhoneList();
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    pers.protobuf.Phone.PhoneDetail getDayPhone(int index);
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    int getDayPhoneCount();
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    java.util.List<? extends pers.protobuf.Phone.PhoneDetailOrBuilder> 
        getDayPhoneOrBuilderList();
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    pers.protobuf.Phone.PhoneDetailOrBuilder getDayPhoneOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code pers.protobuf.DayOfPhone}
   */
  public static final class DayOfPhone extends
      com.google.protobuf.GeneratedMessage
      implements DayOfPhoneOrBuilder {
    // Use DayOfPhone.newBuilder() to construct.
    private DayOfPhone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DayOfPhone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DayOfPhone defaultInstance;
    public static DayOfPhone getDefaultInstance() {
      return defaultInstance;
    }

    public DayOfPhone getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DayOfPhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dayPhone_ = new java.util.ArrayList<pers.protobuf.Phone.PhoneDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              dayPhone_.add(input.readMessage(pers.protobuf.Phone.PhoneDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dayPhone_ = java.util.Collections.unmodifiableList(dayPhone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_DayOfPhone_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_DayOfPhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.protobuf.Phone.DayOfPhone.class, pers.protobuf.Phone.DayOfPhone.Builder.class);
    }

    public static com.google.protobuf.Parser<DayOfPhone> PARSER =
        new com.google.protobuf.AbstractParser<DayOfPhone>() {
      public DayOfPhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DayOfPhone(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DayOfPhone> getParserForType() {
      return PARSER;
    }

    // repeated .pers.protobuf.PhoneDetail DayPhone = 1;
    public static final int DAYPHONE_FIELD_NUMBER = 1;
    private java.util.List<pers.protobuf.Phone.PhoneDetail> dayPhone_;
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    public java.util.List<pers.protobuf.Phone.PhoneDetail> getDayPhoneList() {
      return dayPhone_;
    }
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    public java.util.List<? extends pers.protobuf.Phone.PhoneDetailOrBuilder> 
        getDayPhoneOrBuilderList() {
      return dayPhone_;
    }
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    public int getDayPhoneCount() {
      return dayPhone_.size();
    }
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    public pers.protobuf.Phone.PhoneDetail getDayPhone(int index) {
      return dayPhone_.get(index);
    }
    /**
     * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
     */
    public pers.protobuf.Phone.PhoneDetailOrBuilder getDayPhoneOrBuilder(
        int index) {
      return dayPhone_.get(index);
    }

    private void initFields() {
      dayPhone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDayPhoneCount(); i++) {
        if (!getDayPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dayPhone_.size(); i++) {
        output.writeMessage(1, dayPhone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dayPhone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dayPhone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pers.protobuf.Phone.DayOfPhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pers.protobuf.Phone.DayOfPhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pers.protobuf.Phone.DayOfPhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pers.protobuf.Phone.DayOfPhone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pers.protobuf.DayOfPhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pers.protobuf.Phone.DayOfPhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_DayOfPhone_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_DayOfPhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.protobuf.Phone.DayOfPhone.class, pers.protobuf.Phone.DayOfPhone.Builder.class);
      }

      // Construct using pers.protobuf.Phone.DayOfPhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDayPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dayPhoneBuilder_ == null) {
          dayPhone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dayPhoneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.protobuf.Phone.internal_static_com_bjsxt_hbase_DayOfPhone_descriptor;
      }

      public pers.protobuf.Phone.DayOfPhone getDefaultInstanceForType() {
        return pers.protobuf.Phone.DayOfPhone.getDefaultInstance();
      }

      public pers.protobuf.Phone.DayOfPhone build() {
        pers.protobuf.Phone.DayOfPhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pers.protobuf.Phone.DayOfPhone buildPartial() {
        pers.protobuf.Phone.DayOfPhone result = new pers.protobuf.Phone.DayOfPhone(this);
        int from_bitField0_ = bitField0_;
        if (dayPhoneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dayPhone_ = java.util.Collections.unmodifiableList(dayPhone_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dayPhone_ = dayPhone_;
        } else {
          result.dayPhone_ = dayPhoneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.protobuf.Phone.DayOfPhone) {
          return mergeFrom((pers.protobuf.Phone.DayOfPhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.protobuf.Phone.DayOfPhone other) {
        if (other == pers.protobuf.Phone.DayOfPhone.getDefaultInstance()) return this;
        if (dayPhoneBuilder_ == null) {
          if (!other.dayPhone_.isEmpty()) {
            if (dayPhone_.isEmpty()) {
              dayPhone_ = other.dayPhone_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDayPhoneIsMutable();
              dayPhone_.addAll(other.dayPhone_);
            }
            onChanged();
          }
        } else {
          if (!other.dayPhone_.isEmpty()) {
            if (dayPhoneBuilder_.isEmpty()) {
              dayPhoneBuilder_.dispose();
              dayPhoneBuilder_ = null;
              dayPhone_ = other.dayPhone_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dayPhoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDayPhoneFieldBuilder() : null;
            } else {
              dayPhoneBuilder_.addAllMessages(other.dayPhone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDayPhoneCount(); i++) {
          if (!getDayPhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.protobuf.Phone.DayOfPhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.protobuf.Phone.DayOfPhone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .pers.protobuf.PhoneDetail DayPhone = 1;
      private java.util.List<pers.protobuf.Phone.PhoneDetail> dayPhone_ =
        java.util.Collections.emptyList();
      private void ensureDayPhoneIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dayPhone_ = new java.util.ArrayList<pers.protobuf.Phone.PhoneDetail>(dayPhone_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pers.protobuf.Phone.PhoneDetail, pers.protobuf.Phone.PhoneDetail.Builder, pers.protobuf.Phone.PhoneDetailOrBuilder> dayPhoneBuilder_;

      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public java.util.List<pers.protobuf.Phone.PhoneDetail> getDayPhoneList() {
        if (dayPhoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dayPhone_);
        } else {
          return dayPhoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public int getDayPhoneCount() {
        if (dayPhoneBuilder_ == null) {
          return dayPhone_.size();
        } else {
          return dayPhoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public pers.protobuf.Phone.PhoneDetail getDayPhone(int index) {
        if (dayPhoneBuilder_ == null) {
          return dayPhone_.get(index);
        } else {
          return dayPhoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder setDayPhone(
          int index, pers.protobuf.Phone.PhoneDetail value) {
        if (dayPhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneIsMutable();
          dayPhone_.set(index, value);
          onChanged();
        } else {
          dayPhoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder setDayPhone(
          int index, pers.protobuf.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneBuilder_ == null) {
          ensureDayPhoneIsMutable();
          dayPhone_.set(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder addDayPhone(pers.protobuf.Phone.PhoneDetail value) {
        if (dayPhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneIsMutable();
          dayPhone_.add(value);
          onChanged();
        } else {
          dayPhoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder addDayPhone(
          int index, pers.protobuf.Phone.PhoneDetail value) {
        if (dayPhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneIsMutable();
          dayPhone_.add(index, value);
          onChanged();
        } else {
          dayPhoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder addDayPhone(
          pers.protobuf.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneBuilder_ == null) {
          ensureDayPhoneIsMutable();
          dayPhone_.add(builderForValue.build());
          onChanged();
        } else {
          dayPhoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder addDayPhone(
          int index, pers.protobuf.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneBuilder_ == null) {
          ensureDayPhoneIsMutable();
          dayPhone_.add(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder addAllDayPhone(
          Iterable<? extends pers.protobuf.Phone.PhoneDetail> values) {
        if (dayPhoneBuilder_ == null) {
          ensureDayPhoneIsMutable();
          super.addAll(values, dayPhone_);
          onChanged();
        } else {
          dayPhoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder clearDayPhone() {
        if (dayPhoneBuilder_ == null) {
          dayPhone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dayPhoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public Builder removeDayPhone(int index) {
        if (dayPhoneBuilder_ == null) {
          ensureDayPhoneIsMutable();
          dayPhone_.remove(index);
          onChanged();
        } else {
          dayPhoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public pers.protobuf.Phone.PhoneDetail.Builder getDayPhoneBuilder(
          int index) {
        return getDayPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public pers.protobuf.Phone.PhoneDetailOrBuilder getDayPhoneOrBuilder(
          int index) {
        if (dayPhoneBuilder_ == null) {
          return dayPhone_.get(index);  } else {
          return dayPhoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public java.util.List<? extends pers.protobuf.Phone.PhoneDetailOrBuilder> 
           getDayPhoneOrBuilderList() {
        if (dayPhoneBuilder_ != null) {
          return dayPhoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dayPhone_);
        }
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public pers.protobuf.Phone.PhoneDetail.Builder addDayPhoneBuilder() {
        return getDayPhoneFieldBuilder().addBuilder(
            pers.protobuf.Phone.PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public pers.protobuf.Phone.PhoneDetail.Builder addDayPhoneBuilder(
          int index) {
        return getDayPhoneFieldBuilder().addBuilder(
            index, pers.protobuf.Phone.PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pers.protobuf.PhoneDetail DayPhone = 1;</code>
       */
      public java.util.List<pers.protobuf.Phone.PhoneDetail.Builder> 
           getDayPhoneBuilderList() {
        return getDayPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pers.protobuf.Phone.PhoneDetail, pers.protobuf.Phone.PhoneDetail.Builder, pers.protobuf.Phone.PhoneDetailOrBuilder> 
          getDayPhoneFieldBuilder() {
        if (dayPhoneBuilder_ == null) {
          dayPhoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pers.protobuf.Phone.PhoneDetail, pers.protobuf.Phone.PhoneDetail.Builder, pers.protobuf.Phone.PhoneDetailOrBuilder>(
                  dayPhone_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dayPhone_ = null;
        }
        return dayPhoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pers.protobuf.DayOfPhone)
    }

    static {
      defaultInstance = new DayOfPhone(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pers.protobuf.DayOfPhone)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bjsxt_hbase_DayOfPhone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bjsxt_hbase_DayOfPhone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013phone.proto\022\017pers.protobuf\"G\n\013PhoneD" +
      "etail\022\014\n\004dnum\030\001 \002(\t\022\016\n\006length\030\002 \002(\t\022\014\n\004t" +
      "ype\030\003 \002(\t\022\014\n\004date\030\004 \002(\t\"<\n\nDayOfPhone\022.\n" +
      "\010DayPhone\030\001 \003(\0132\034.pers.protobuf.PhoneD" +
      "etail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bjsxt_hbase_PhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bjsxt_hbase_PhoneDetail_descriptor,
              new String[] { "Dnum", "Length", "Type", "Date", });
          internal_static_com_bjsxt_hbase_DayOfPhone_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bjsxt_hbase_DayOfPhone_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bjsxt_hbase_DayOfPhone_descriptor,
              new String[] { "DayPhone", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
